// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Achievements","status":true,"description":"Pivert Achievements system.","parameters":{"-- Achievements --":"","Achievements text":"Achievements","Achievement unlocked text":"Achievement unlocked!","Achievement unlocked timer":"240","Achievement unlocked SE":"Item1","-- Settings --":"","Initial switch":"500","Images directory":"img/achievements","Locked image":"locked"}}
];
