// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Achievements","status":true,"description":"Pivert Achievements system.","parameters":{"-- Achievements --":"","Achievements text":"Achievements","Ach. unlocked text":"Achievement unlocked!","Ach. unlocked timer":"180","Ach. unlocked SE":"Item1","Ach. unlocked width":"480","Ach. unlocked X position":"0","Ach. unlocked Y position":"0","Locked ach. name color":"5","Unlocked ach. name color":"0","-- Settings --":"","Images directory":"img/achievements","Locked image":"locked"}}
];
